import path from 'path';
import { DetectedPattern, Improvement } from '../types/index.js';
import { readTextFile } from '../utils/file-utils.js';
import { scoreToImpact } from '../utils/pattern-detector.js';

interface ClaudeMdRule {
  section: string;
  content: string;
  reason: string;
}

export class ClaudeMdGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  async generateFromPatterns(patterns: DetectedPattern[]): Promise<Improvement | null> {
    const rules = this.extractRules(patterns);
    if (rules.length === 0) return null;

    const existingContent = await readTextFile(path.join(this.projectRoot, 'CLAUDE.md')) ?? '';
    const patch = this.buildPatch(rules, existingContent);
    if (!patch.additions) return null;

    const topScore = Math.max(...patterns.map((p) => Math.round(p.confidence * 80 + p.frequency * 2)));
    const score = Math.min(topScore, 90);

    return {
      id: 'claude-md-update',
      type: 'claude-md',
      name: 'CLAUDE.md',
      reason: `${rules.length} new rules derived from detected patterns`,
      impact: scoreToImpact(score),
      score,
      pattern: patterns[0], // representative pattern
      outputPath: 'CLAUDE.md',
      generatedContent: patch.newContent,
    };
  }

  private extractRules(patterns: DetectedPattern[]): ClaudeMdRule[] {
    const rules: ClaudeMdRule[] = [];

    for (const pattern of patterns) {
      switch (pattern.type) {
        case 'code-error': {
          const errors = (pattern.metadata?.['errors'] as Array<{ snippet: string }>) ?? [];
          if (errors.some((e) => e.snippet.includes('any'))) {
            rules.push({
              section: 'TypeScript',
              content: '- Never use `any` type — use `unknown`, generics, or explicit interfaces instead',
              reason: 'Repeated `any` usage detected in codebase',
            });
          }
          if (errors.some((e) => e.snippet.includes('return type'))) {
            rules.push({
              section: 'TypeScript',
              content: '- Always add explicit return types to exported functions',
              reason: 'Missing return types detected',
            });
          }
          if (errors.some((e) => e.snippet.includes('null'))) {
            rules.push({
              section: 'TypeScript',
              content: '- Always check for null/undefined before accessing nested properties',
              reason: 'Null-check errors detected',
            });
          }
          break;
        }

        case 'user-correction': {
          const corrections = (pattern.metadata?.['corrections'] as Array<{ correction: string }>) ?? [];
          for (const c of corrections.slice(0, 2)) {
            if (c.correction.length < 150) {
              rules.push({
                section: 'Code Style',
                content: `- ${c.correction.replace(/\n/g, ' ').slice(0, 120)}`,
                reason: 'User correction recorded',
              });
            }
          }
          break;
        }

        case 'missing-rule': {
          const modules = (pattern.metadata?.['modules'] as Array<{ module: string }>) ?? [];
          if (modules.length > 0) {
            rules.push({
              section: 'Dependencies',
              content: `- Prefer these established libraries: ${modules.slice(0, 5).map((m) => `\`${m.module}\``).join(', ')}`,
              reason: 'Frequently used modules detected',
            });
          }
          break;
        }

        case 'repetitive-workflow': {
          const label = pattern.metadata?.['label'] as string;
          if (label) {
            rules.push({
              section: 'Workflows',
              content: `- Use the \`/${label}\` command for ${label.replace(/-/g, ' ')} tasks`,
              reason: `Workflow repeated ${pattern.frequency} times`,
            });
          }
          break;
        }
      }
    }

    return rules;
  }

  private buildPatch(rules: ClaudeMdRule[], existing: string): { additions: boolean; newContent: string } {
    const sectionMap = new Map<string, string[]>();

    for (const rule of rules) {
      // Skip rules already present in CLAUDE.md
      if (existing.toLowerCase().includes(rule.content.toLowerCase().slice(2, 40))) {
        continue;
      }
      const section = sectionMap.get(rule.section) ?? [];
      section.push(`${rule.content} <!-- ${rule.reason} -->`);
      sectionMap.set(rule.section, section);
    }

    if (sectionMap.size === 0) {
      return { additions: false, newContent: existing };
    }

    const newSections: string[] = [];
    for (const [section, lines] of sectionMap) {
      newSections.push(`\n## ${section} (auto-generated by claude-improver)\n\n${lines.join('\n')}`);
    }

    const addition = newSections.join('\n');
    const newContent = existing
      ? `${existing.trimEnd()}\n\n---\n${addition}\n`
      : `# Project Rules\n\nAuto-generated by claude-improver on ${new Date().toISOString()}\n${addition}\n`;

    return { additions: true, newContent };
  }
}
