import { DetectedPattern, Improvement } from '../types/index.js';
import { scoreImpact, scoreToImpact } from '../utils/pattern-detector.js';

export class PromptGenerator {
  generateFromPattern(pattern: DetectedPattern): Improvement | null {
    if (pattern.type !== 'repeated-prompt') return null;
    if (pattern.frequency < 3) return null;

    const phrase = (pattern.metadata?.['phrase'] as string) ?? pattern.examples[0] ?? 'task';
    const name = phrase
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .slice(0, 40);

    const score = scoreImpact(pattern.frequency, pattern.confidence, 40);
    const outputPath = `.claude/prompts/${name}.md`;

    return {
      id: `prompt-${name}`,
      type: 'prompt',
      name,
      reason: `Prompt "${phrase}" used ${pattern.frequency} times — save as reusable template`,
      impact: scoreToImpact(score),
      score,
      pattern,
      outputPath,
      generatedContent: this.renderPromptTemplate(name, phrase, pattern),
    };
  }

  private renderPromptTemplate(name: string, phrase: string, pattern: DetectedPattern): string {
    const examples = pattern.examples.slice(0, 5).map((e, i) => `### Example ${i + 1}\n\n> ${e}`).join('\n\n');

    return `---
name: ${name}
description: Reusable prompt template for "${phrase}"
version: 1.0.0
auto-generated: true
generated-at: ${new Date().toISOString()}
frequency: ${pattern.frequency}
---

# Prompt Template: ${name}

## Base prompt

\`\`\`
${phrase}
\`\`\`

## Enhanced version

\`\`\`
${this.enhancePrompt(phrase)}
\`\`\`

## Detected usage examples

${examples || '_No examples recorded_'}

## Variables

You can customize this template with variables:

| Variable | Description | Example |
|----------|-------------|---------|
| \`{{target}}\` | The target file or module | \`src/api/users.ts\` |
| \`{{framework}}\` | The project framework | \`Express\`, \`NestJS\` |
| \`{{style}}\` | Code style preference | \`functional\`, \`OOP\` |

## Usage

Paste this template and fill in the variables, or use it as a starting point for your request.

---
_Auto-generated by claude-improver — edit to match your exact needs_
`;
  }

  private enhancePrompt(base: string): string {
    const enhanced = base.trim();
    // Add context hints to the prompt
    return `${enhanced}

Context:
- Target: {{target}}
- Follow project conventions
- Use existing patterns and utilities where possible
- Ensure all edge cases are handled
- Add tests if applicable`;
  }
}
