#!/usr/bin/env node
/**
 * claude-improver MCP server
 *
 * Tools:
 *   1. improve_yourself_analyze  – run analyzers and return raw patterns for Claude to act on
 *   2. improve_yourself_apply    – write improvements generated by Claude to disk
 *   3. improve_yourself_history  – show previously applied improvements
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  Tool,
} from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';
import path from 'path';
import { runAnalyze } from './commands/improve-yourself.js';
import { ImprovementHistoryStore } from './storage/improvement-history.js';
import { writeTextFile } from './utils/file-utils.js';

// ── Tool definitions ──────────────────────────────────────────────────────────

const TOOLS: Tool[] = [
  {
    name: 'improve_yourself_analyze',
    description:
      'Analyze the project git history and conversation sessions to detect recurring patterns. Returns raw patterns with context — YOU (Claude) generate the actual skill/command/CLAUDE.md content from these patterns.',
    inputSchema: {
      type: 'object',
      properties: {
        project_root: {
          type: 'string',
          description: 'Absolute path to the project root. Defaults to cwd.',
        },
      },
    },
  },
  {
    name: 'improve_yourself_apply',
    description:
      'Write improvements to disk and record them in history. Pass the improvements you generated from the analyze output.',
    inputSchema: {
      type: 'object',
      required: ['improvements'],
      properties: {
        improvements: {
          type: 'array',
          description: 'List of improvements to write to disk.',
          items: {
            type: 'object',
            required: ['id', 'name', 'type', 'outputPath', 'content'],
            properties: {
              id: { type: 'string', description: 'Unique ID (use the pattern id as base, e.g. "skill-add-i18n-key")' },
              name: { type: 'string', description: 'Human-readable name' },
              type: { type: 'string', enum: ['skill', 'command', 'claude-md', 'prompt'] },
              outputPath: { type: 'string', description: 'Relative path from project root (e.g. ".claude/skills/add-i18n-key/SKILL.md")' },
              content: { type: 'string', description: 'Full file content to write' },
            },
          },
        },
        rejected_ids: {
          type: 'array',
          items: { type: 'string' },
          description: 'Pattern IDs the user rejected — will not be proposed again.',
        },
        project_root: {
          type: 'string',
          description: 'Absolute path to the project root.',
        },
      },
    },
  },
  {
    name: 'improve_yourself_history',
    description: 'Show the history of improvements that have been applied to this project.',
    inputSchema: {
      type: 'object',
      properties: {
        project_root: {
          type: 'string',
          description: 'Absolute path to the project root.',
        },
      },
    },
  },
];

// ── Zod schemas ───────────────────────────────────────────────────────────────

const AnalyzeSchema = z.object({
  project_root: z.string().optional(),
});

const ImprovementInputSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.enum(['skill', 'command', 'claude-md', 'prompt']),
  outputPath: z.string(),
  content: z.string(),
});

const ApplySchema = z.object({
  improvements: z.array(ImprovementInputSchema).min(1),
  rejected_ids: z.array(z.string()).optional(),
  project_root: z.string().optional(),
});

const HistorySchema = z.object({
  project_root: z.string().optional(),
});

// ── Server setup ──────────────────────────────────────────────────────────────

const server = new Server(
  { name: 'claude-improver', version: '1.0.0' },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case 'improve_yourself_analyze': {
        const { project_root } = AnalyzeSchema.parse(args ?? {});
        const projectRoot = project_root ?? process.cwd();

        const result = await runAnalyze(projectRoot);

        return {
          content: [{ type: 'text', text: result.formattedOutput }],
        };
      }

      case 'improve_yourself_apply': {
        const { improvements, rejected_ids, project_root } = ApplySchema.parse(args ?? {});
        const projectRoot = project_root ?? process.cwd();
        const store = new ImprovementHistoryStore(projectRoot);

        const applied: string[] = [];
        const errors: string[] = [];

        for (const imp of improvements) {
          try {
            const fullPath = path.join(projectRoot, imp.outputPath);
            await writeTextFile(fullPath, imp.content);
            applied.push(`  ✓ ${imp.outputPath}  (${imp.type})`);
          } catch (err) {
            errors.push(`  ✗ ${imp.outputPath}: ${err instanceof Error ? err.message : String(err)}`);
          }
        }

        // Record applied improvements in history
        if (applied.length > 0) {
          await store.record(
            improvements
              .filter((_, i) => !errors.some((e) => e.includes(improvements[i].outputPath)))
              .map((imp) => ({
                id: imp.id,
                name: imp.name,
                type: imp.type,
                outputPath: imp.outputPath,
                generatedContent: imp.content,
                reason: '',
                impact: 'medium' as const,
                score: 0,
                pattern: { id: imp.id, type: 'repetitive-workflow' as const, frequency: 0, examples: [], confidence: 0 },
              })),
          );
        }

        // Record rejections
        if (rejected_ids && rejected_ids.length > 0) {
          await store.recordRejections(
            rejected_ids.map((id) => ({
              id,
              name: id,
              type: 'skill' as const,
              outputPath: '',
              generatedContent: '',
              reason: '',
              impact: 'low' as const,
              score: 0,
              pattern: { id, type: 'repetitive-workflow' as const, frequency: 0, examples: [], confidence: 0 },
            })),
          );
        }

        const lines = [`Applied ${applied.length} improvement(s):`, '', ...applied];
        if (errors.length > 0) lines.push('', `Errors (${errors.length}):`, ...errors);

        return { content: [{ type: 'text', text: lines.join('\n') }] };
      }

      case 'improve_yourself_history': {
        const { project_root } = HistorySchema.parse(args ?? {});
        const projectRoot = project_root ?? process.cwd();
        const store = new ImprovementHistoryStore(projectRoot);
        const history = await store.renderHistory();
        return { content: [{ type: 'text', text: history }] };
      }

      default:
        return { content: [{ type: 'text', text: `Unknown tool: ${name}` }], isError: true };
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { content: [{ type: 'text', text: `Error: ${message}` }], isError: true };
  }
});

// ── Start ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('claude-improver MCP server started\n');
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err}\n`);
  process.exit(1);
});
